:page-layout: getting-started
:page-title: First lines of code
:page-description: Your first lines of code using Mutiny
:page-previous: Getting Started
:page-previous-href: /getting-started/getting-started
:page-next: Creating Unis
:page-next-href: /getting-started/creating-unis
:page-liquid: 

Once you made Mutiny available to your classpath, you can start writing code.
Let's start with this simple program:

[source, java]
----
import io.smallrye.mutiny.Uni;

public class FirstProgram {

  public static void main(String[] args) {
    Uni.createFrom().item("hello")
      .onItem().transform(item -> item + " mutiny")
      .onItem().transform(String::toUpperCase)
      .subscribe().with(
        item -> System.out.println(">> " + item)
    );
  }

}
----

This program prints ">> HELLO MUTINY".
What's interesting is how this message is _built_.
We described a processing pipeline taking an item, processing it and finally consuming it. 
First, we create a `Uni`, one of the two types provided by Mutiny.
A `Uni` is a stream emitting either a single item or a failure. 
Here, we create a `Uni` emitting the "hello" item, this is the input of our pipeline.
Then we process this item.
First we append " mutiny", then we make it uppercase.
This form the processing part of our pipeline
Finally, we **subscribe**.

This last part is essential.
If you don't have a final subscriber, nothing is going to happen.
Mutiny types are lazy, meaning that you need to express your interest.
If you don't, the computation won't even start.

IMPORTANT: If your program does not do anything, verify you didn't forget to subscribe.

Another important aspect is the pipeline construction.
Appending a new stage to a pipeline returns a new `Uni.`
The previous program is equivalent to:

[source, java]
----
Uni<String> uni1 = Uni.createFrom().item("hello");
Uni<String> uni2 = uni1.onItem().transform(item -> item + " mutiny");
Uni<String> uni3 = uni2.onItem().transform(String::toUpperCase);

uni3
      .subscribe().with(
        item -> System.out.println(">> " + item)
    );
----

It's fundamental to understand that this program is not equivalent to:

[source, java]
----
Uni<String> uni = Uni.createFrom().item("hello");
uni.onItem().transform(item -> item + " mutiny");
uni.onItem().transform(String::toUpperCase);

uni
      .subscribe().with(
        item -> System.out.println(">> " + item)
    );
----

This program just prints ">> hello".
It does not use the appended stages as the final subscriber consumes the first `Uni.`