:page-layout: getting-started
:page-title: Creating Multis
:page-desc: Learn how to create Multi instances
:page-previous: Creating Unis
:page-previous-href: /getting-started/creating-unis
:page-next: Transforming items
:page-next-href: /getting-started/transforming-items
:page-liquid: 

== Creating Multis

A `Multi` represents a _stream_ of data.
This stream can emit 0, 1, n, or an infinite number of items.
You rarely create instances of `Multi` yourself, but, instead, use a reactive client exposing a Mutiny API that provides `Multi.` 
That being said, it can be handy at times.

=== The Multi type

A `Multi<T>` is a data stream that:

* emit 0..n item events
* emit a failure event
* emit a completion event for bounded stream

[WARNING]
====
Failures are terminal events. After a failure, no other items will be emitted.
====

`Multi<T>` provides many operators that create, transform, and orchestrate `Multi` sequences.
The offered operators can be used to define a processing pipeline.
The events flow in this pipeline, and each operator can process or transform the events.
`Multis` are lazy by nature. 
To trigger the computation, you must have a final subscriber indicating your interest.
The following snippet provides a simple example of pipeline using `Multi`:

.Example of pipeline using Multi
[source, java, indent=0]
----
Multi.createFrom().items(1, 2, 3, 4, 5)
    .onItem().transform(i -> i * 2)
    .transform().byTakingFirstItems(3)
    .onFailure().recoverWithItem(0)
    .subscribe().with(System.out::println);
----

You can see the `Multi` javadoc https://javadoc.io/static/io.smallrye.reactive/mutiny/{{ site.data.versions.mutiny_version }}/index.html?io/smallrye/mutiny/Multi.html[here].

=== Subscribing to a Multi

Remember, if you don't subscribe, nothing is going to happen.
Also, the pipeline is materialized for each _subscription_.

When subscribing to a `Multi,` you can pass an item callback (invoked when the item is emitted), or pass two callbacks, one receiving the item and one receiving the failure, or three callbacks to handle respectively the item, failure and completion events.

[source, java, indent=0]
----
Cancellable cancellable = multi
    .subscribe().with(
        item -> System.out.println(item),
        failure -> System.out.println("Failed with " + failure),
        () -> System.out.println("Completed")
    );
----

Note the returned `Cancellable.` 
This object allows canceling the stream if needed.

=== Creating Multi from items

There are many ways to create `Multi` instances. 
Use https://javadoc.io/static/io.smallrye.reactive/mutiny/{{ site.data.versions.mutiny_version }}/index.html?io/smallrye/mutiny/groups/MultiCreate.html[Multi.createFrom()] to see all the possibilities.

You can, for instance, create a `Multi` from a known items or from `Iterables`:

[source, java]
----
Uni<Integer> uni = Uni.createFrom().items(1, 2, 3, 4);
Multi.createFrom().iterable(Arrays.asList(1, 2, 3, 4, 5))
----

Every subscriber receives the same set of items (`1`, `2`... `5`) just after the subscription.

You can also use `Suppliers`:

[source, java]
----
AtomicInteger counter = new AtomicInteger();
Multi.createFrom().items(() ->
    IntStream.range(counter.getAndIncrement(), counter.get() * 2).boxed()
)
----

The `Supplier` is called for every subscriber. 
So, each of them will get different values.

[TIP]
====
You can create ranges using `Multi.createFrom().range`.
====

=== Creating failing Multis

Streams can also fail.
Failures are used to indicate to the downstream subscribers that the source encountered a terrible error and cannot continue emitting items.
Create failed `Multi` instances with:

[source, java]
----
// Pass an exception directly:
Multi<Integer> failed1 = Multi.createFrom().failure(new Exception("boom"));
// Pass a supplier called for every subscriber:
Multi<Integer> failed2 = Multi.createFrom().failure(() -> new Exception("boom"));
----

=== Creating empty Multis

Unlike `Unis,` `Multis` don't send `null` item.
They send a completion event indicating that there are no more items to consume.
Of course, the completion event can happen even if there are no items, creating an empty stream.

You can create such a stream using:

[source, java]
----
Multi<T> multi = Multi.createFrom().empty();
----

=== Creating Multis using an emitter (_advanced_)

You can also create a `Multi` using an emitter.
This approach is useful when integrating callback-based APIs:

[source, java]
----
Multi.createFrom().emitter(em -> {
    em.emit(1);
    em.emit(2);
    em.emit(3);
    em.complete();
});
----

The emitter can also send a failure.
It can also get notified of cancellation to, for example, stop the work in progress.

=== Creating Multis from _ticks_ (_advanced_)

You can create a stream that emit a _ticks_ periodically:

[source, java]
----
Multi<Long> ticks = Multi.createFrom().ticks().every(Duration.ofMillis(100));
----

The downstream receives a `long,` which is a counter. 
For the first tick, it's 0, then 1, then 2, and so on.

