---
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Build and Deploy
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_TOKEN }}
        run: |
          sudo apt-get install graphviz default-jdk 
          ./scripts/build-site.sh
          git config --global user.email "clement@apache.org"
          git config --global user.name "Clement Escoffier"
          ./scripts/deploy-to-github-pages.sh

