---
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'  

      - name: Build and Deploy
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_TOKEN }}
        run: |
          sudo apt-get update
          sudo apt-get install graphviz default-jdk 
          echo "Installing required gems"
          gem install bundler
          gem install jekyll
          echo "Installing site required gems"
          bundle install
          ./scripts/build-site.sh
          git config --global user.email "clement@apache.org"
          git config --global user.name "Clement Escoffier"
          ./scripts/deploy-to-github-pages.sh

